# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
                ('event_date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('org_name', models.CharField(max_length=200)),
                ('org_website', models.CharField(max_length=200)),
                ('org_email', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=200)),
            ],
        ),
    ]
